# Generated by Django 6.0.2 on 2026-03-08 10:34

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='Номер класса')),
                ('label_ru', models.CharField(blank=True, help_text='Напр. «5 класс»', max_length=50, verbose_name='Подпись (рус)')),
                ('label_kk', models.CharField(blank=True, max_length=50, verbose_name='Подпись (каз)')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='LessonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Модель урока',
                'verbose_name_plural': 'Модели урока',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LessonOrganizationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Форма организации урока',
                'verbose_name_plural': 'Формы организации урока',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Тип урока',
                'verbose_name_plural': 'Типы уроков',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер четверти')),
                ('label_ru', models.CharField(blank=True, max_length=50, verbose_name='Подпись (рус)')),
                ('label_kk', models.CharField(blank=True, max_length=50, verbose_name='Подпись (каз)')),
            ],
            options={
                'verbose_name': 'Четверть',
                'verbose_name_plural': 'Четверти',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=300, verbose_name='Название (рус)')),
                ('name_kk', models.CharField(blank=True, max_length=300, verbose_name='Название (каз)')),
                ('name_en', models.CharField(blank=True, max_length=300, verbose_name='Название (eng)')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Код предмета')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['order', 'name_ru'],
            },
        ),
        migrations.CreateModel(
            name='SubjectArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=300, verbose_name='Название (рус)')),
                ('name_kk', models.CharField(blank=True, max_length=300, verbose_name='Название (каз)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Образовательная область',
                'verbose_name_plural': 'Образовательные области',
                'ordering': ['order', 'name_ru'],
            },
        ),
        migrations.CreateModel(
            name='TeachingMethodology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Методика обучения',
                'verbose_name_plural': 'Методики обучения',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LongTermPlanSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('kk', 'Казахский'), ('en', 'Английский')], default='ru', max_length=5, verbose_name='Язык обучения')),
                ('name_ru', models.CharField(max_length=500, verbose_name='Название раздела (рус)')),
                ('name_kk', models.CharField(blank=True, max_length=500, verbose_name='Название раздела (каз)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('hours', models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во часов')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='curriculum.gradelevel', verbose_name='Класс')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='curriculum.quarter', verbose_name='Четверть')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='curriculum.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Раздел долгосрочного плана',
                'verbose_name_plural': 'Разделы долгосрочного плана',
                'ordering': ['grade__number', 'quarter__number', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LexicalSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=500, verbose_name='Лексический раздел (рус)')),
                ('name_kk', models.CharField(blank=True, max_length=500, verbose_name='Лексический раздел (каз)')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lexical_sections', to='curriculum.gradelevel', verbose_name='Класс')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lexical_sections', to='curriculum.quarter', verbose_name='Четверть')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lexical_sections', to='curriculum.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Лексический раздел',
                'verbose_name_plural': 'Лексические разделы',
            },
        ),
        migrations.CreateModel(
            name='EducationActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=300, verbose_name='Вид деятельности (рус)')),
                ('name_kk', models.CharField(blank=True, max_length=300, verbose_name='Вид деятельности (каз)')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_types', to='curriculum.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Вид учебной деятельности',
                'verbose_name_plural': 'Виды учебной деятельности',
                'ordering': ['name_ru'],
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='curriculum.subjectarea', verbose_name='Образовательная область'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=500, verbose_name='Название темы (рус)')),
                ('name_kk', models.CharField(blank=True, max_length=500, verbose_name='Название темы (каз)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('hours', models.PositiveSmallIntegerField(default=1, verbose_name='Кол-во часов')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='curriculum.longtermplansection', verbose_name='Раздел долгосрочного плана')),
            ],
            options={
                'verbose_name': 'Тема урока',
                'verbose_name_plural': 'Темы уроков',
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LearningObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Напр. 5.1.1.1', max_length=30, verbose_name='Код цели обучения')),
                ('text_ru', models.TextField(verbose_name='Текст цели обучения (рус)')),
                ('text_kk', models.TextField(blank=True, verbose_name='Текст цели обучения (каз)')),
                ('bloom_level', models.CharField(blank=True, help_text='remembering / understanding / applying / analyzing / evaluating / creating', max_length=30, verbose_name='Уровень таксономии Блума')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='curriculum.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Цель обучения',
                'verbose_name_plural': 'Цели обучения',
                'ordering': ['topic', 'order', 'code'],
            },
        ),
    ]
