# Generated by Django 6.0.2 on 2026-03-03 09:00

import django.db.models.deletion
import lessons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('step', 'Этап урока'), ('slide', 'Слайд')], max_length=20)),
                ('index', models.PositiveSmallIntegerField(default=0)),
                ('prompt_text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=lessons.models.lesson_image_upload_path)),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lessons.lessonplan')),
            ],
            options={
                'ordering': ['kind', 'index'],
                'unique_together': {('lesson_plan', 'kind', 'index')},
            },
        ),
    ]
