# Generated by Django 6.0.2 on 2026-03-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lessonplanimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='tool_type',
            field=models.CharField(choices=[('lesson_plan', 'План урока'), ('sor_soch', 'СОР/СОЧ'), ('formative', 'Формативное оценивание'), ('structural', 'Структурные задания'), ('presentation', 'Презентация'), ('feedback', 'Обратная связь')], default='lesson_plan', max_length=30),
        ),
    ]
