# Generated by Django 6.0.2 on 2026-03-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lessonplan_tool_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='tool_type',
            field=models.CharField(choices=[('lesson_plan', 'План урока'), ('sor_soch', 'СОР/СОЧ'), ('formative', 'Формативное оценивание'), ('structural', 'Структурные задания'), ('presentation', 'Презентация'), ('feedback', 'Обратная связь'), ('organizer', 'Органайзер')], default='lesson_plan', max_length=30),
        ),
    ]
